---
title: "Moving the Gates"
format: html
---

Alright, let's try to move the gates.

```{r}
library(flowWorkspace)
devtools::document("/home/david/Documents/Luciernaga")
devtools::load_all("/home/david/Documents/Luciernaga")
devtools::document("/home/david/Documents/flowGate")
devtools::load_all("/home/david/Documents/flowGate")
```

# Reload attempt

```{r}
Beads <- list.files("/home/david/Documents/SDY3080/data/SDY3080/SingleColor_BeadReferences_00", full.names=TRUE, pattern=".fcs")

OurGateTemplate <- "/home/david/Desktop/openCytoTemplate.csv"
GatesToApply <- data.table::fread(OurGateTemplate)
TheFullTemplate <- gatingTemplate(GatesToApply)
```

```{r}
SFC_cytoset <- load_cytoset_from_fcs(Beads,
 truncate_max_range = FALSE, transformation = FALSE)
SFC_GatingSet <- GatingSet(SFC_cytoset)

gt_gating(TheFullTemplate, SFC_GatingSet)
```

```{r}
gs_apply_gate_check(gs=SFC_GatingSet[1:3], gate="scatter")
```

```{r}
gs_pop_get_gate(SFC_GatingSet, "scatter")
```



# Original

```{r}
SFC_GatingSet <- load_gs("data/BeadsGS.gs")
```

```{r}
plot(SFC_GatingSet)
```

```{r}
devtools::document("/home/david/Documents/flowGate")
devtools::load_all("/home/david/Documents/flowGate")

gs_to_openCyto(gs=SFC_GatingSet, sample=1, outpath="/home/david/Desktop")
```







# Testing Suite

```{r}
#gs_apply_gate_check(
gs <- SFC_GatingSet
gate <- "singlets"
sample <- 1
#)

      if(is.null(sample)){
        Samples <- seq_along(gs)
      } else {Samples <- sample}

sample <- Samples
```






# Testing

```{r}
gs_apply_gate_check(gs=SFC_GatingSet[1:3], gate="scatter")
```

```{r}
plot(SFC_GatingSet)
```

```{r}
ggcyto::autoplot(SFC_GatingSet[[4]], gate="scatter", bins=300)

gs_pop_get_gate(SFC_GatingSet, "scatter")
```

```{r}
ggcyto::autoplot(SFC_GatingSet[[3]], gate="scatter", bins=300)
```







```{r}
?gs_pop_add()

?gs_pop_set_gate()
```

```{r}
ggcyto::autoplot(SFC_GatingSet[[1]], gate="scatter", bins=300)
```

```{r}
rg <- rectangleGate("FSC-A"=c(0,1E6), "SSC-A"=c(2E6, 3E6),
        filterId="rectangle")

gs_pop_add(SFC_GatingSet[1], gate=rg, parent="singlets")

recompute(SFC_GatingSet)

gs_pop_get_gate(SFC_GatingSet[1], "rectangle")

rg <- rectangleGate("FSC-A"=c(0,2E6), "SSC-A"=c(2E6, 4E6),
        filterId="rectangle")

TheList <- list(rg)

names(TheList) <- sampleNames(SFC_GatingSet[1])

gs_pop_set_gate(SFC_GatingSet[1], "rectangle", TheList)
recompute(SFC_GatingSet)

gs_pop_get_gate(SFC_GatingSet[1], "rectangle")

plot(SFC_GatingSet)

gs_pop_get_count_fast(SFC_GatingSet[1])
```

```{r}
gs_pop_get_count_fast(SFC_GatingSet)
```

```{r}
#gs_apply_gate_check(
x <- SFC_GatingSet
gate <- "singlets"
sample <- 1
#)

sample <- Samples
```




```{r}
plot(SFC_GatingSet)
```

```{r}
Singlets <- gs_pop_get_gate(SFC_GatingSet, "singlets")

Hmm <- Singlets$`DTR_2023_ILT_00-Reference Group-4BeadsUnstained (Beads).1237095.fcs`
Hmm@boundaries
Hmm@parameters
Hmm@filterId

str(Singlets)
```